name: kgtkr-auto-update-release

on:
  pull_request:
    types: [closed]
    branches:
      - kgtkr-master

jobs:
  release:
    if: github.event.pull_request.merged == true && startsWith(github.event.pull_request.head.ref, 'update/v')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.PAT }}

      - run: |
          git config --global user.name "kgtkr actions"
          git config --global user.email "actions@kgtkr.net"

      - run: |
          HEAD_REF="${{ github.event.pull_request.head.ref }}"
          VERSION="${HEAD_REF#update/v}"

          ./kgtkr-update.sh release "$VERSION"

          VERSION_ARR=(${VERSION//./ })
          MINOR_VERSION=${VERSION_ARR[0]}.${VERSION_ARR[1]}

          git push origin "kgtkr-$MINOR_VERSION"
          git push -f origin mstdn.kgtkr.net
