name: kgtkr-update
on:
  workflow_dispatch:
    inputs:
      version:
        type: string
        description: 'The version of Mastodon'
        required: true
permissions:
  contents: write
jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - run: |
          git config --global user.name "kgtkr actions"
          git config --global user.email "actions@kgtkr.net"
          cat <<EOF > ~/.netrc
          machine github.com
          login ${{ secrets.GITHUB_ACTOR }}
          password ${{ secrets.PAT }}
          EOF
      - run: GIT_MERGE_AUTOEDIT=no ./kgtkr-update.sh "$VERSION"
        env:
          VERSION: ${{ github.event.inputs.version }}
